{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgresql.config.password | quote }}
{{- end }}

