apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-app

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - kafka-deployment.yaml
  - backend-deployment.yaml
  - consumer-deployment.yaml
  - frontend-deployment.yaml

commonLabels:
  project: task-manager
  managed-by: kustomize

